Hydra-core supports Python 3.9
conda-forge/hydra-core-feedstock pull request #10
Opened 2021-01-22 18:33 UTC by alanhdu

See https://github.com/facebookresearch/hydra/blob/d097e2f089122d2c9c95cbc0fbfb63387aef2309/setup.py#L52

2021-01-22 18:33 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-01-22 18:40 UTC, omry requested changes

2021-01-22 18:40 UTC, omry commented on recipe/meta.yaml
>      - omegaconf >=2.0.2
can you update the omegaconf dependency to:
```
omegaconf>=2.0.5,<2.1
```
Per the [requirements](https://github.com/facebookresearch/hydra/blob/1.0_branch/requirements/requirements.txt) of Hydra 1.0?

Also, importlib_resources is only needed for Python < 3.9.

2021-01-22 19:06 UTC, alanhdu commented
I updated the omegaconf dependency, but am not sure how to update the `importlib-resources` dependency: https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python says that `noarch` doesn't support selectors, so I'm not sure how to represent that.

2021-01-22 19:07 UTC, omry commented
Okay, let's see if anyone else has an idea.
importlib-resoruces is a weird one but I think it's pretty common.
there are probably other projects with the same issue.

2021-02-03 15:47 UTC, alanhdu commented
Is there anything else I can do to help along the review? I looked into the `noarch` dependency on Python version selectors, but couldn't find any guidance (I would've assumed this was a common problem, but looking ta other `noarch` dependencies they seem to just install the extra dependency).

2021-02-03 20:18 UTC, omry approved these changes
If the standard approach is to just install the extra dependency I think we can go with it.
Please add a comment before merging.

2021-02-03 20:18 UTC, omry commented on recipe/meta.yaml
>      - importlib_resources
Can you add a comment this is only needed in Python < 3.9?
At some point we will be able to remove it.

2021-02-04 20:49 UTC, omry approved these changes
lgtm but I don't have merge access.
@hadim ?

2021-02-04 21:01 UTC, hadim commented
@omry do you want to be a maintainer?

2021-02-04 21:22 UTC, omry commented
I don't mind rubber stamping but I don't have the time to learn how to actually maintain the conda package.
feel free to add me but I would still need help.

2021-02-04 21:27 UTC, merged

2021-02-04 21:36 UTC, hadim commented
Not much more to what you already did in that PR actually :-)